version: '3'
services:
  notebin-service:
    build: ./notebin-service
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://master_postgres:5432/note_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pswd
      - SPRING_REDIS_HOST=master_redis
      - SPRING_REDIS_PORT=6379
      - AUTH_CLIENT_HOST=user-service
      - AUTH_CLIENT_PORT=8081
    depends_on:
      - user-service
      - master_redis

  user-service:
    build: ./user-service
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://master_postgres:5432/note_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pswd
    depends_on:
      - master_postgres

  master_postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pswd
      POSTGRES_DB: note_db
    ports:
      - '5432:5432'

  master_redis:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
  frontend:
    build: ./frontend/frontend
    ports: 
      - '3000:80'
